# Configuraci贸n de la BD
database:
  host: 127.0.0.1
  port: 3306
  database: teams
  username: root
  password: putillas

# Configuraci贸n general
settings:
  default-language: es_ES
  max-team-size: 4 # incluyendo al l铆der
  invite-expiration-time: 60 # en segundos

# Configuraci贸n de mensajes
messages:
  prefix: "<dark_gray>[</dark_gray><color:#bdecb6></color><dark_gray>]</dark_gray>  "
  colors:
    primary: "<#55FFFF>"
    secondary: "<#AAFFFF>"
    error: "<#FF5555>"

# Configuraci贸n de sonidos
sounds:
  team_create: ENTITY_PLAYER_LEVELUP
  team_disband: ENTITY_IRON_GOLEM_DEATH
  team_join: ENTITY_PLAYER_LEVELUP
  team_leave: ENTITY_VILLAGER_NO
  invite_send: BLOCK_NOTE_BLOCK_PLING
  invite_receive: ENTITY_EXPERIENCE_ORB_PICKUP
